# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff95e33ae15ee1a0f9f31a393d48f5b802fa8a3cd1e7ad0817c3d4a9a8f9c5d8df0bea55ea22a05db81d5eb2443917b4eb9de33dddba4666cc94337a63e35f4e

test:
  secret_key_base: 06db200446a0edf8401f0dad0bc1280a00445d9501b90a39c27f777231cf8fa632e87138ece9ce7372123c62366921ab422e73b4fe1762dfbb9f95c85ca8e0e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
